# Host entry point for the "nixos-btw" machine
# This file imports all system-level configuration for this host
{
  imports = [
    # Hardware-specific configuration (auto-generated by nixos-generate-config)
    ./hardware-configuration.nix
    
    # Shared NixOS modules (core, packages, services)
    ../../modules/nixos
  ];
}
