# Hyprland Configuration (Out-of-Store)

# Monitor
monitor = ,preferred,auto,1

# Execute on start
exec-once = dms run

# Env vars
env = XCURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME,qt5ct # change to qt6ct if you have that

# Input
input {
    kb_layout = us
    follow_mouse = 1
    touchpad {
        natural_scroll = no
    }
}

# General
general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = rgba(00ff99ee)
    col.inactive_border = rgba(595959aa)
    layout = dwindle
}

# Decoration
decoration {
    rounding = 10
    blur {
        enabled = true
        size = 3
        passes = 1
    }
    shadow {
        enabled = true
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }
}

# Animations
animations {
    enabled = true
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

# Dwindle
dwindle {
}

# Master
master {
    new_status = master
}

# Gestures
gestures {
}

# Keybinds
$mainMod = SUPER

bind = $mainMod, RETURN, exec, kitty
bind = $mainMod, Q, killactive
bind = $mainMod SHIFT, Q, exit
bind = $mainMod, E, exec, dolphin
bind = $mainMod, F, fullscreen
bind = $mainMod, V, togglefloating
bind = $mainMod, SPACE, exec, dms ipc call spotlight toggle
bind = $mainMod, P, pseudo # dwindle
bind = $mainMod, J, layoutmsg, togglesplit # dwindle

# Move focus
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# Switch workspaces
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5

# Move active window to workspace
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5

# Special Keys Binding
bindel = , XF86AudioRaiseVolume, exec, pamixer -i 5
bindel = , XF86AudioLowerVolume, exec, pamixer -d 5
bindl = , XF86AudioMute, exec, pamixer -t
bindl = , XF86AudioMicMute, exec, pamixer --default-source -t
bindel = , XF86MonBrightnessUp, exec, brightnessctl set +10%
bindel = , XF86MonBrightnessDown, exec, brightnessctl set 10%-
bind = , XF86KbdBrightnessUp, exec, brightnessctl -d spi::kbd_backlight set +10%
bind = , XF86KbdBrightnessDown, exec, brightnessctl -d spi::kbd_backlight set 10%-

bind = , Print, exec, sh -c 'DIR="$HOME/Pictures/Screenshots"; mkdir -p "$DIR"; FILE="$DIR/$(date +%Y-%m-%d_%H-%M-%S).png"; grim "$FILE" && cat "$FILE" | wl-copy && notify-send "Screenshot saved" "$FILE"'
bind = $mainMod, S, exec, sh -c 'DIR="$HOME/Pictures/Screenshots"; mkdir -p "$DIR"; FILE="$DIR/$(date +%Y-%m-%d_%H-%M-%S).png"; grim -g "$(slurp)" "$FILE" && cat "$FILE" | wl-copy && notify-send "Screenshot saved" "$FILE"'

# Mouse bindings
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
