[ColorScheme]
active_colors=#211b0d, #fff8f1, #faecd5, #847656, #f3e1bb, #d6c5a0, #211b0d, #ffffff, #211b0d, #fff8f1, #fff8f1, #000000, #9a4523, #ffffff, #8f4c33, #8f4c33, #fff2dc, #fff8f1, #fff8f1, #51452a, #51452a
disabled_colors=#51452a, #f3e1bb, #faecd5, #847656, #f3e1bb, #d6c5a0, #51452a, #51452a, #51452a, #f3e1bb, #f3e1bb, #000000, #f3e1bb, #51452a, #51452a, #51452a, #f3e1bb, #f3e1bb, #f3e1bb, #51452a, #51452a
inactive_colors=#51452a, #fff8f1, #faecd5, #847656, #f3e1bb, #d6c5a0, #51452a, #51452a, #51452a, #fff8f1, #fff8f1, #000000, #8f4c33, #ffffff, #8f4c33, #8f4c33, #fff2dc, #fff8f1, #fff8f1, #51452a, #51452a

[ColorEffects:Disabled]
Color=81,69,42
ColorAmount=0
ColorEffect=0
ContrastAmount=0.65
ContrastEffect=1
IntensityAmount=0.1
IntensityEffect=2

[ColorEffects:Inactive]
ChangeSelectionColor=true
Color=132,118,86
ColorAmount=0.025
ColorEffect=2
ContrastAmount=0.1
ContrastEffect=2
Enable=false
IntensityAmount=0
IntensityEffect=0

[Colors:Button]
BackgroundAlternate=250,236,213
BackgroundNormal=255,248,241
DecorationFocus=154,69,35
DecorationHover=154,69,35
ForegroundActive=154,69,35
ForegroundInactive=81,69,42
ForegroundLink=117,91,11
ForegroundNegative=186,26,26
ForegroundNeutral=143,76,51
ForegroundNormal=33,27,13
ForegroundPositive=117,91,11
ForegroundVisited=143,76,51

[Colors:Complementary]
BackgroundAlternate=250,236,213
BackgroundNormal=255,248,241
DecorationFocus=154,69,35
DecorationHover=154,69,35
ForegroundActive=154,69,35
ForegroundInactive=81,69,42
ForegroundLink=117,91,11
ForegroundNegative=186,26,26
ForegroundNeutral=143,76,51
ForegroundNormal=33,27,13
ForegroundPositive=117,91,11
ForegroundVisited=143,76,51

[Colors:Header]
BackgroundAlternate=255,248,241
BackgroundNormal=255,248,241
DecorationFocus=154,69,35
DecorationHover=154,69,35
ForegroundActive=154,69,35
ForegroundInactive=81,69,42
ForegroundLink=117,91,11
ForegroundNegative=186,26,26
ForegroundNeutral=143,76,51
ForegroundNormal=33,27,13
ForegroundPositive=117,91,11
ForegroundVisited=143,76,51

[Colors:Header][Inactive]
BackgroundAlternate=255,248,241
BackgroundNormal=255,248,241
DecorationFocus=154,69,35
DecorationHover=154,69,35
ForegroundActive=154,69,35
ForegroundInactive=81,69,42
ForegroundLink=117,91,11
ForegroundNegative=186,26,26
ForegroundNeutral=143,76,51
ForegroundNormal=33,27,13
ForegroundPositive=117,91,11
ForegroundVisited=143,76,51

[Colors:Selection]
BackgroundAlternate=255,219,207
BackgroundNormal=154,69,35
DecorationFocus=154,69,35
DecorationHover=154,69,35
ForegroundActive=255,255,255
ForegroundInactive=81,69,42
ForegroundLink=117,91,11
ForegroundNegative=186,26,26
ForegroundNeutral=143,76,51
ForegroundNormal=255,255,255
ForegroundPositive=117,91,11
ForegroundVisited=143,76,51

[Colors:Tooltip]
BackgroundAlternate=255,248,241
BackgroundNormal=255,248,241
DecorationFocus=154,69,35
DecorationHover=154,69,35
ForegroundActive=154,69,35
ForegroundInactive=81,69,42
ForegroundLink=117,91,11
ForegroundNegative=186,26,26
ForegroundNeutral=143,76,51
ForegroundNormal=33,27,13
ForegroundPositive=117,91,11
ForegroundVisited=143,76,51

[Colors:View]
BackgroundAlternate=255,242,220
BackgroundNormal=255,248,241
DecorationFocus=154,69,35
DecorationHover=154,69,35
ForegroundActive=154,69,35
ForegroundInactive=81,69,42
ForegroundLink=117,91,11
ForegroundNegative=186,26,26
ForegroundNeutral=143,76,51
ForegroundNormal=33,27,13
ForegroundPositive=117,91,11
ForegroundVisited=143,76,51

[Colors:Window]
BackgroundAlternate=255,248,241
BackgroundNormal=255,248,241
DecorationFocus=154,69,35
DecorationHover=154,69,35
ForegroundActive=154,69,35
ForegroundInactive=81,69,42
ForegroundLink=117,91,11
ForegroundNegative=186,26,26
ForegroundNeutral=143,76,51
ForegroundNormal=33,27,13
ForegroundPositive=117,91,11
ForegroundVisited=143,76,51

[WM]
activeBackground=255,248,241
activeBlend=33,27,13
activeForeground=33,27,13
inactiveBackground=255,248,241
inactiveBlend=81,69,42
inactiveForeground=81,69,42
