cursor #ebdfe9
cursor_text_color #d2c2d2

foreground            #ebdfe9
background            #171118
selection_foreground  #482536
selection_background  #ecb8ce
url_color             #74d7ca

color0   #171118
color1   #f79e6f
color2   #6bd772
color3   #fff372
color4   #5bccbd
color5   #0f6358
color6   #74d7ca
color7   #d4e1df
color8   #818b8a
color9   #ffc09f
color10  #a5ffab
color11  #fff7a5
color12  #8fece0
color13  #acfff4
color14  #cafff8
color15  #f8fffe
