cursor #211b0d
cursor_text_color #51452a

foreground            #211b0d
background            #fff8f1
selection_foreground  #ffffff
selection_background  #ffb59a
url_color             #9a4523

color0   #181306
color1   #920f0a
color2   #157300
color3   #b89700
color4   #a1431e
color5   #ffd1bf
color6   #9a4523
color7   #2b2928
color8   #827f7d
color9   #c83d35
color10  #34a919
color11  #c8a300
color12  #bb4d22
color13  #ffd1bf
color14  #c8907a
color15  #e6e1df
