cursor #d8e5e9
cursor_text_color #b2cbd2

foreground            #d8e5e9
background            #091518
selection_foreground  #003826
selection_background  #8cd5b3
url_color             #6bdbad

color0   #091518
color1   #fb9a6e
color2   #6bdb6f
color3   #fff26f
color4   #50d09b
color5   #06653e
color6   #6bdbad
color7   #d7e5e0
color8   #838e89
color9   #ffbb9d
color10  #a3ffa7
color11  #fff6a3
color12  #88f0c5
color13  #a3ffd9
color14  #c4ffe6
color15  #f8fffc
