-- Auto-generated by DMS Matugen hook — do not edit manually.
-- Remove require("dms.colors") from hyprland.lua to override.

hl.config({
	general = {
		col = {
			active_border = "rgb(9a4523)",
			inactive_border = "rgb(847656)",
		},
	},
	group = {
		col = {
			border_active = "rgb(9a4523)",
			border_inactive = "rgb(847656)",
			border_locked_active = "rgb(ba1a1a)",
			border_locked_inactive = "rgb(847656)",
		},
		groupbar = {
			col = {
				active = "rgb(9a4523)",
				inactive = "rgb(847656)",
				locked_active = "rgb(ba1a1a)",
				locked_inactive = "rgb(847656)",
			},
		},
	},
})
