-- Auto-generated by DMS — do not edit manually

hl.env("HYPRCURSOR_THEME", "Capitaine Cursors (Gruvbox)")
hl.env("XCURSOR_THEME", "Capitaine Cursors (Gruvbox)")
hl.env("HYPRCURSOR_SIZE", "42")
hl.env("XCURSOR_SIZE", "42")
